### PR TITLE
slider resets num fix

### LINKED ISSUE #60: Mouse up on transform input field clears value
When selecting a value in an input field (e.g. ty) you often end up hovering over the tx field slider symbol. When lifting the mouse button while on this icon the tx value gets cleared and undo doesn’t even bring it back.

6d4ed56c2f07df0770319629fb807f7422da250f

### PR DESCRIPTION
**Pull request by LeXXik**
Fixes #60

### CODE REVIEW

File: src/components/NumericInput/index.js [hunk 1]
```diff
@@ -77,6 +77,7 @@ class NumericInput extends TextInput {
                 this._sliderControl.dom.requestPointerLock();
                 this._sliderMovement = 0.0;
                 this._sliderPrevValue = this.value;
+                this._sliderUsed = true;
```
Comment (vkalpias) [inline src/components/NumericInput/index.js:80]: This looks good but could we make the `_sliderUsed` variable a local boolean instead of a NumericInput property as it's not used anywhere else?

Comment (LeXXik) [reply src/components/NumericInput/index.js:80]: Good point. I will update it.

**Review by vkalpias — APPROVED** [review]
